### ISSUE TITLE
Expecting 'STRING','NUMBER','NULL','TRUE','FALSE','{','[', got EOF

### ISSUE THREAD

**Issue by meiyingping** [18380435477/WeApp#3]
你好，我在把代码拉下来之后，运行直接报错：
`VM315:2 pages/ws/ws.json
Expecting 'STRING','NUMBER','NULL','TRUE','FALSE','{','[', got EOF
    | ^(anonymous function) @ VM315:2`
该文件为空！

**Comment by meiyingping** [comment]
只要在该文件里面加`{}`就可以正常运行了。

**Comment by liujians** [comment]
嗯、版本更新遗留的问题、感谢指出
